language: node_js
node_js:
  - 0.10
branches:
  only:
    - test
install:
  - npm install
before_script:
  - npm run servers & # in the background
notifications:
  email:
    recipients:
      - om@soundsapiens.com
    on_success: change
    on_failure: always
