language: node_js
node_js:
  - 0.10
branches:
  only:
    - active
install:
  - npm install
before_script:
  - npm run servers &
  - ./node_modules/.bin/wait-up $(./node_modules/.bin/coffee ./test/make-uri.coffee)
notifications:
  email:
    recipients:
      - om@soundsapiens.com
    on_success: change
    on_failure: always
